env:
  es6: true
  node: true
  jest: true

plugins:
  - "no-only-tests"

extends:
  - "eslint:recommended"
  - "plugin:node/recommended"

parserOptions:
  ecmaVersion: 2020

# when updating, please copy to other projects <3
# code */.eslintrc.yml
rules:
  arrow-spacing: error
  complexity: [ error, 6 ]
  curly: [ error, all ]
  indent: [ error, 2 ]
  key-spacing: [ error, { beforeColon: false } ]
  linebreak-style: [ error, unix ]
  no-console: [ error ]
  no-process-exit: off
  no-trailing-spaces: [ error ]
  quotes: [ error, single ]
  semi: [ error, always ]
  space-infix-ops: [ error ]
  strict: [ error, "global" ]
  no-shadow: error
  no-only-tests/no-only-tests: [ error ]
