env:
  es6: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:node/recommended
parserOptions:
  ecmaVersion: 2020
rules:
  indent: [ error, 2 ]
  linebreak-style: [ error, unix ]
  quotes: [ error, single ]
  semi: [ error, always ]
  curly: [ error, all ]
  no-console: [ error ]
  complexity: [ error, 6 ]
  strict: [ error, global ]
  space-infix-ops: [error]
  key-spacing: [ error, { beforeColon: false } ]
  no-trailing-spaces: [ error ]
  no-process-exit: off
