on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:

jobs:
  test:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: yarn install --immutable
      - run: yarn test --ci
  lint:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: yarn install --immutable
      - run: yarn lint

  checks:
    if: always()
    needs: [ test, lint ]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Fail if any required job failed or was cancelled
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
