on:
  push:
    tags: [ 'v*' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@^11.5.1
      - run: yarn install --immutable
      - run: scripts/version-tag-validate.js ${{ github.ref }}
      - run: npm publish --access public
